// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  carousel: dynamic(() => import('./Carousel')),
  company_info: dynamic(() => import('./CompanyInfo')),
  news: dynamic(() => import('./News')),
  service_overview: dynamic(() => import('./ServiceOverview')),
}
